[package]
name = "raytracing_in_one_weekend"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.22"
rayon = "*"
rand_distr = "*"
rand = "*"


[lib]
name = "raytracing_in_one_weekend"
path = "lib/lib.rs"

[[bin]]
name = "raytracing_in_one_weekend"
path = "src/main.rs"